version: '3.7'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  backend:
    build: ./backend/
    volumes:
      - "./backend/:/app"
      - "/app/node_modules"
    environment:
      VIRTUAL_HOST: "backend.${HOST}"
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - mongodb
      - nginx-proxy
    expose:
      - 3000
    command: "npm run ${MODE}"
  
  frontend:
    build: ./frontend/
    volumes:
      - "./frontend/:/app"
      - "/app/node_modules"
    environment:
      VIRTUAL_HOST: ${HOST}
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - nginx-proxy
      - backend
    expose:
      - 3000
    command: "npm run ${MODE}"

  mongodb:
    image: mongo
    volumes:
      - "mongodata:/data/db"
    ports:
      - "27017:27017"

volumes:
  mongodata:
    
