version: '3.7'

services:
  nginx-proxy-prod:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy-prod
    depends_on:
        - backend-prod
        - frontend-prod
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  backend-prod:
    build: 
      context: ./backend/
      dockerfile: ../docker/prod/backend/Dockerfile
    environment:
      VIRTUAL_HOST: backend.localhost
    expose:
      - 3000

  frontend-prod:
    build: 
      context: ./frontend
      dockerfile: ../docker/prod/frontend/Dockerfile
    environment:
      VIRTUAL_HOST: localhost
    expose:
      - 3000

  mongodb:
    image: mongo
    volumes:
      - "mongodata:/data/db"
    ports:
      - "27017:27017"

volumes:
  mongodata: