version: '3.7'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  backend:
    build: 
      context: ./backend/
      dockerfile: "Dockerfile-${MODE}"
    volumes:
      - "${BACKEND_BIND_MOUNT}"
      - "${CACHED_NODE_MODULES}"
    depends_on:
        - mongodb
        - nginx-proxy
    environment:
      VIRTUAL_HOST: "backend.${HOST}"
      CHOKIDAR_USEPOLLING: "${HOTRELOAD}"
    expose:
      - 3000

  frontend:
    build: 
      context: ./frontend/
      dockerfile: "Dockerfile-${MODE}"
    volumes:
      - "${FRONTEND_BIND_MOUNT}"
      - "${CACHED_NODE_MODULES}"
    depends_on:
      - nginx-proxy
    environment:
      VIRTUAL_HOST: ${HOST}
      CHOKIDAR_USEPOLLING: "${HOTRELOAD}"
    expose:
      - 3000

  mongodb:
    image: mongo
    volumes:
      - "mongodata:/data/db"
    ports:
      - "27017:27017"

volumes:
  mongodata: